# Groundstation Configuration
[network]
local_ip = "0.0.0.0" # Listen on all interfaces
host_ip = "127.0.0.1" # Local IP for connections
root_sensor_dir = "/home/kush-mahajan/sensor_system"
port_min = 8000 # Minimum port number
keyboard_background = true

# Telemetry settings
[telemetry]
groundstation_flag = true # Enable groundstation mode
groundstation_ip = "0.0.0.0" # Listen on all interfaces
publish_port = 2240         # Port for streaming telemetry packets
local_socket_buffer_size = 1024    # Local socket write buffer size (bytes)

# Database settings
[database]
host = "0.0.0.0"  # Listen on all interfaces
port = 2240
max_connections = 10
log_level = "info"

# Sensor data viewer settings
[viewer]
enabled = true
update_rate_hz = 1
display_format = "table"  # table, json, csv
show_timestamps = true
filter_sensors = []  # Empty means show all sensors

# Message IDs for database
[MessageIDs]
PTMessage = 1
TCMessage = 2
RTDMessage = 3
IMUMessage = 4
BarometerMessage = 5
GPSPositionMessage = 6
GPSVelocityMessage = 7


