# Jetson Sensor System Configuration
[network]
local_ip = "127.0.0.1" # Local IP for connections
groundstation_ip = "192.168.1.100" # Groundstation IP address (CHANGE THIS TO YOUR LAPTOP IP)
root_sensor_dir = "/home/kush-mahajan/sensor_system"
port_min = 8000 # Minimum port number
keyboard_background = true

# Telemetry settings
[telemetry]
groundstation_flag = true # Enable connection to groundstation
groundstation_ip = "192.168.1.100" # Groundstation IP address (CHANGE THIS TO YOUR LAPTOP IP)
publish_port = 2240         # Port for streaming telemetry packets
local_socket_buffer_size = 1024    # Local socket write buffer size (bytes)

# PT Sensor settings
[pt_sensor]
enabled = true
publish_port = 8001
publish_max_clients = 3
logger_flag = false
max_buffer = 10
pressure_range_min = 95000.0  # Pa
pressure_range_max = 105000.0 # Pa
temperature_range_min = 20.0  # C
temperature_range_max = 30.0  # C
update_rate_hz = 10

# TC Sensor settings
[tc_sensor]
enabled = true
publish_port = 8002
publish_max_clients = 3
logger_flag = false
max_buffer = 10
temperature_range_min = 100.0  # C
temperature_range_max = 200.0  # C
voltage_range_min = 0.001      # V
voltage_range_max = 0.010      # V
tc_type = 0  # Type K thermocouple
update_rate_hz = 5

# RTD Sensor settings
[rtd_sensor]
enabled = true
publish_port = 8003
publish_max_clients = 3
logger_flag = false
max_buffer = 10
temperature_range_min = 15.0   # C
temperature_range_max = 35.0   # C
resistance_range_min = 95.0    # Ohm
resistance_range_max = 105.0   # Ohm
rtd_type = 0  # PT100
update_rate_hz = 2

# IMU Sensor settings
[imu_sensor]
enabled = true
publish_port = 8004
publish_max_clients = 3
logger_flag = false
max_buffer = 10
accel_noise_std = 0.01  # m/s^2
gyro_noise_std = 0.001  # rad/s
gravity_magnitude = 9.81 # m/s^2
update_rate_hz = 100

# Barometer Sensor settings
[barometer_sensor]
enabled = true
publish_port = 8005
publish_max_clients = 3
logger_flag = false
max_buffer = 10
pressure_range_min = 95000.0  # Pa
pressure_range_max = 105000.0 # Pa
altitude_range_min = -10.0    # m
altitude_range_max = 10.0     # m
temperature_range_min = 20.0  # C
temperature_range_max = 30.0  # C
update_rate_hz = 20

# GPS Sensor settings
[gps_sensor]
enabled = true
publish_port = 8006
publish_max_clients = 3
logger_flag = false
max_buffer = 10
latitude_range_min = 37.7     # deg
latitude_range_max = 37.8     # deg
longitude_range_min = -122.5  # deg
longitude_range_max = -122.4  # deg
altitude_range_min = 0.0      # m
altitude_range_max = 100.0    # m
velocity_range_min = -5.0     # m/s
velocity_range_max = 5.0      # m/s
horizontal_accuracy = 2.5     # m
vertical_accuracy = 3.0       # m
speed_accuracy = 0.5          # m/s
satellites_used = 8
update_rate_hz = 1

# Message IDs for database
[MessageIDs]
PTMessage = 1
TCMessage = 2
RTDMessage = 3
IMUMessage = 4
BarometerMessage = 5
GPSPositionMessage = 6
GPSVelocityMessage = 7


